name: "Setup Deno Environment"
description: "Sets up the Deno environment for the build"
inputs:
  deno-version:
    description: "The version of Deno to install"
    required: true
    default: "v1.x"
runs:
  using: "composite"
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ inputs.deno-version }}
    - name: Set Deno cache dir
      shell: bash
      run: echo "DENO_DIR=$RUNNER_TEMP${{ runner.os == 'Windows' && '\\' || '/'  }}deno_cache" >> $GITHUB_ENV
    - name: Cache Deno Deps
      id: cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os}}-deno-${{ hashFiles('./deno.lock') }}
        path: ${{ env.DENO_DIR }}