import { EmoteDefinition } from "Types/EmoteDefinition";
import { GameEvents } from "Types/GameEvents";
import EventEmitter from "Utilities/EventEmitter";

export type EmoteType = (typeof GameData.EmotePersonaIdMap)[keyof typeof GameData.EmotePersonaIdMap];

export default class GameData {
    static readonly events = new EventEmitter<GameEvents>();

    static readonly DetectableBlocks = ["log", "ore", "door", "chest"] as const;

    static readonly MaxSerializableAiPlayers = 10;

    static readonly HungerConsumption = {
        movementCheckIterval: 40,
        moving: -0.2,
        notMoving: 0,
        mineBlock: -0.5,
        attack: -1,
        heal: -6,
    };

    static readonly HungerMaxValue = 40;
    static readonly HungerExhaustionThreshold = 10; // If hunger is lower than this number, ai player will get slowed down
    static readonly HungerDamageThreshold = 2; // If hunger is lower than this number, ai player will start taking damage

    static readonly ExhaustionSlownessAmplifier = 2; // If hunger is lower than this number, ai player will get slowed down
    static readonly HungerDamageAmount = 1; // If hunger is lower than this number, ai player will start taking damage
    static readonly HungerDamageInterval = 80; // How often the ai player takes damage while starving

    // Both of these below must pass to heal from hunger
    static readonly HealFromHungerHealthThreshhold = 18; // If health is lower than this number, allow healing from hunger; Max health is 20
    static readonly HealFromHungerHungerThreshhold = 30; // If hunger is higher than this number, allow healing from hunger
    static readonly HealFromHungerInterval = 40;
    static readonly HealFromHungerHealthAmount = 4; // The amount to increase health by. Hunger consumption is defined in HungerConsumption.heal

    static readonly FoodValues = {
        // crops
        "minecraft:potato": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 1, saturation: 0.6 },
        "minecraft:poisonous_potato": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 2, saturation: 1.2 },
        "minecraft:melon_slice": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 2, saturation: 1.2 },
        "minecraft:glow_berries": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 2, saturation: 0.4 },
        "minecraft:sweet_berries": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 2, saturation: 1.2 },
        "minecraft:golden_carrot": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 6, saturation: 14.4 },
        "minecraft:golden_apple": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 4, saturation: 9.6 },
        "minecraft:enchanted_golden_apple": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 4, saturation: 9.6 },
        "minecraft:chorus_fruit": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 4, saturation: 2.4 },
        "minecraft:carrot": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 3, saturation: 3.6 },
        "minecraft:beetroot": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 1, saturation: 1.2 },
        "minecraft:apple": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 4, saturation: 2.4 },
        // meat
        "minecraft:rotten_flesh": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 4, saturation: 0.8 },
        "minecraft:porkchop": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 3, saturation: 1.8 },
        "minecraft:mutton": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 2, saturation: 1.2 },
        "minecraft:rabbit": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 3, saturation: 1.8 },
        "minecraft:chicken": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 2, saturation: 1.2 },
        "minecraft:beef": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 3, saturation: 1.8 },
        // fish
        "minecraft:tropical_fish": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 1, saturation: 0.2 },
        "minecraft:salmon": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 2, saturation: 0.4 },
        "minecraft:pufferfish": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 1, saturation: 0.2 },
        "minecraft:cod": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 2, saturation: 0.4 },
        // cooked food
        "minecraft:cooked_salmon": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 6, saturation: 9.6 },
        "minecraft:cooked_rabbit": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 5, saturation: 6 },
        "minecraft:cooked_porkchop": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 8, saturation: 12.8 },
        "minecraft:cooked_mutton": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 6, saturation: 9.6 },
        "minecraft:cooked_cod": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 5, saturation: 6 },
        "minecraft:cooked_chicken": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 6, saturation: 7.2 },
        "minecraft:cooked_beef": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 8, saturation: 12.8 },
        // crafted dishes
        "minecraft:suspicious_stew": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 6, saturation: 7.2 },
        "minecraft:rabbit_stew": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 10, saturation: 12 },
        "minecraft:pumpkin_pie": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 8, saturation: 4.8 },
        "minecraft:mushroom_stew": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 6, saturation: 7.2 },
        "minecraft:dried_kelp": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 1, saturation: 0.2 },
        "minecraft:cookie": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 2, saturation: 0.4 },
        "minecraft:bread": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 5, saturation: 6 },
        "minecraft:beetroot_soup": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 6, saturation: 7.2 },
        "minecraft:baked_potato": { hungerRegeneration: 10, healthRegeneration: 2, foodPoints: 5, saturation: 6 },
    };

    static readonly EmotePersonaIdMap = {
        "17428c4c-3813-4ea1-b3a9-d6a32f83afca": "Follow Me",
        "ce5c0300-7f03-455d-aaf1-352e4927b54d": "Over There",
    } as const;

    static readonly ItemGroup = {
        "minecraft:log": [
            "minecraft:acacia_log",
            "minecraft:birch_log",
            "minecraft:cherry_log",
            "minecraft:dark_oak_log",
            "minecraft:jungle_log",
            "minecraft:mangrove_log",
            "minecraft:oak_log",
            "minecraft:spruce_log",
            "minecraft:crismon_stem",
            "minecraft:warped_stem",
        ],
        "minecraft:door": [
            "minecraft:acacia_door",
            "minecraft:bamboo_door",
            "minecraft:birch_door",
            "minecraft:cherry_door",
            "minecraft:copper_door",
            "minecraft:crimson_door",
            "minecraft:dark_oak_door",
            "minecraft:exposed_copper_door",
            "minecraft:iron_door",
            "minecraft:jungle_door",
            "minecraft:mangrove_door",
            "minecraft:oxidized_copper_door",
            "minecraft:pale_oak_door",
            "minecraft:spruce_door",
            "minecraft:warped_door",
            "minecraft:waxed_copper_door",
            "minecraft:waxed_exposed_copper_door",
            "minecraft:waxed_oxidized_copper_door",
            "minecraft:waxed_weathered_copper_door",
            "minecraft:weathered_copper_door",
            "minecraft:wooden_door",
        ],
        "minecraft:chest": [
            "minecraft:chest", //
            "minecraft:trapped_chest",
        ],
        "minecraft:stone": [
            "minecraft:cobblestone",
            "minecraft:stone",
            "minecraft:andesite",
            "minecraft:diorite",
            "minecraft:granite",
            "minecraft:calcite",
            "minecraft:tuff ",
        ],
        "minecraft:surface": [
            "minecraft:grass_block",
            "minecraft:path_block",
            "minecraft:dirt",
            "minecraft:clay",
            "minecraft:gravel",
            "minecraft:podzol",
            "minecraft:mycelium",
            "minecraft:yellow_terracotta",
            "minecraft:red_terracotta",
            "minecraft:brown_terracotta",
            "minecraft:orange_terracotta",
            "minecraft:terracotta",
            "minecraft:mud",
            "minecraft:waterlily_pad",
            "minecraft:farmland",
            "minecraft:snow",
            "minecraft:snow_layer",
            "minecraft:cobblestone",
            "minecraft:stone",
            "minecraft:red_sandstone",
            "minecraft:sandstone",
            "minecraft:sand",
            "minecraft:red_sand",
        ],
        "minecraft:underground": [
            "minecraft:dirt",
            "minecraft:stone",
            "minecraft:deepslate",
            "minecraft:tuff",
            "minecraft:calcite",
            "minecraft:sculk",
            "minecraft:bedrock",
            "minecraft:granite",
            "minecraft:diorite",
            "minecraft:andersite",
            "minecraft:dripstone_block",
            "minecraft:pointed_dripstone",
            "minecraft:mossy_cobblestone",
            "minecraft:cobblestone",
            "minecraft:gravel",
        ],
        "minecraft:ore": [
            "minecraft:redstone_ore",
            "minecraft:copper_ore",
            "minecraft:diamond_ore",
            "minecraft:emerald_ore",
            "minecraft:gold_ore",
            "minecraft:iron_ore",
            "minecraft:lapis_ore",
            "minecraft:coal_ore",
            "minecraft:deepslate_redstone_ore",
            "minecraft:deepslate_copper_ore",
            "minecraft:deepslate_diamond_ore",
            "minecraft:deepslate_emerald_ore",
            "minecraft:deepslate_gold_ore",
            "minecraft:deepslate_iron_ore",
            "minecraft:deepslate_lapis_ore",
            "minecraft:deepslate_coal_ore",
            "minecraft:nether_gold_ore",
            "minecraft:quartz_ore",
            // "minecraft:stone",
        ],
        "minecraft:resources": [
            "minecraft:coal",
            "minecraft:diamond",
            "minecraft:emerald",
            "minecraft:lapis_lazuli",
            "minecraft:redstone",
            "minecraft:raw_iron",
            "minecraft:raw_gold",
            "minecraft:raw_copper",
            "minecraft:quartz",
            "minecraft:ancient_debris",
            "minecraft:gold_nugget",
            "minecraft:redstone_ore",
            "minecraft:copper_ore",
            "minecraft:diamond_ore",
            "minecraft:emerald_ore",
            "minecraft:gold_ore",
            "minecraft:iron_ore",
            "minecraft:lapis_ore",
            "minecraft:coal_ore",
            "minecraft:deepslate_redstone_ore",
            "minecraft:deepslate_copper_ore",
            "minecraft:deepslate_diamond_ore",
            "minecraft:deepslate_emerald_ore",
            "minecraft:deepslate_gold_ore",
            "minecraft:deepslate_iron_ore",
            "minecraft:deepslate_lapis_ore",
            "minecraft:deepslate_coal_ore",
            "minecraft:nether_gold_ore",
            "minecraft:quartz_ore",
        ],
        "minecraft:copper_blocks": [
            "minecraft:copper_block",
            "minecraft:exposed_copper",
            "minecraft:weathered_copper",
            "minecraft:oxidized_copper",
            "minecraft:waxed_copper",
            "minecraft:waxed_exposed_copper",
            "minecraft:waxed_weathered_copper",
            "minecraft:waxed_oxidized_copper",
            "minecraft:cut_copper",
            "minecraft:exposed_cut_copper",
            "minecraft:weathered_cut_copper",
            "minecraft:oxidized_cut_copper",
            "minecraft:waxed_cut_copper",
            "minecraft:waxed_exposed_cut_copper",
            "minecraft:waxed_weathered_cut_copper",
            "minecraft:waxed_oxidized_cut_copper",
            "minecraft:cut_copper_slab",
            "minecraft:exposed_cut_copper_slab",
            "minecraft:weathered_cut_copper_slab",
            "minecraft:oxidized_cut_copper_slab",
            "minecraft:waxed_cut_copper_slab",
            "minecraft:waxed_exposed_cut_copper_slab",
            "minecraft:waxed_weathered_cut_copper_slab",
            "minecraft:waxed_oxidized_cut_copper_slab",
            "minecraft:cut_copper_stairs",
            "minecraft:exposed_cut_copper_stairs",
            "minecraft:weathered_cut_copper_stairs",
            "minecraft:oxidized_cut_copper_stairs",
            "minecraft:waxed_cut_copper_stairs",
            "minecraft:waxed_exposed_cut_copper_stairs",
            "minecraft:waxed_weathered_cut_copper_stairs",
            "minecraft:waxed_oxidized_cut_copper_stairs",
        ],
        "minecraft:ingot": ["minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:copper_ingot", "minecraft:netherite_ingot"],
        "minecraft:iron": ["minecraft:iron_ore", "minecraft:iron_ingot", "minecraft:raw_iron"],
        "minecraft:gem": ["minecraft:diamond", "minecraft:emerald"],
        "minecraft:diamond": ["minecraft:diamond", "minecraft:diamond_ore"],
        "minecraft:leather": ["minecraft:leather"],
        "minecraft:axe": [
            "minecraft:netherite_axe",
            "minecraft:diamond_axe",
            "minecraft:golden_axe",
            "minecraft:iron_axe",
            "minecraft:stone_axe",
            "minecraft:wooden_axe",
        ],
        "minecraft:shovel": [
            "minecraft:netherite_shovel",
            "minecraft:diamond_shovel",
            "minecraft:golden_shovel",
            "minecraft:iron_shovel",
            "minecraft:stone_shovel",
            "minecraft:wooden_shovel",
        ],
        "minecraft:pickaxe": [
            "minecraft:netherite_pickaxe",
            "minecraft:diamond_pickaxe",
            "minecraft:golden_pickaxe",
            "minecraft:iron_pickaxe",
            "minecraft:stone_pickaxe",
            "minecraft:wooden_pickaxe",
        ],
        "minecraft:sword": [
            "minecraft:netherite_sword",
            "minecraft:diamond_sword",
            "minecraft:golden_sword",
            "minecraft:iron_sword",
            "minecraft:stone_sword",
            "minecraft:wooden_sword",
        ],
        "minecraft:ranged_weapon": ["minecraft:crossbow", "minecraft:bow"],
        "minecraft:weapon": [
            "minecraft:trident",
            "minecraft:netherite_sword",
            "minecraft:diamond_sword",
            "minecraft:golden_sword",
            "minecraft:iron_sword",
            "minecraft:stone_sword",
            "minecraft:wooden_sword",
            "minecraft:netherite_axe",
            "minecraft:diamond_axe",
            "minecraft:golden_axe",
            "minecraft:iron_axe",
            "minecraft:stone_axe",
            "minecraft:wooden_axe",
            "minecraft:netherite_pickaxe",
            "minecraft:diamond_pickaxe",
            "minecraft:golden_pickaxe",
            "minecraft:iron_pickaxe",
            "minecraft:stone_pickaxe",
            "minecraft:wooden_pickaxe",
        ],
        "minecraft:all_food": [
            // crops
            "minecraft:potato",
            "minecraft:poisonous_potato",
            "minecraft:melon_slice",
            "minecraft:glow_berries",
            "minecraft:sweet_berries",
            "minecraft:golden_carrot",
            "minecraft:golden_apple",
            "minecraft:enchanted_golden_apple",
            "minecraft:chorus_fruit",
            "minecraft:carrot",
            "minecraft:beetroot",
            "minecraft:apple",
            // meat
            "minecraft:rotten_flesh",
            "minecraft:porkchop",
            "minecraft:mutton",
            "minecraft:rabbit",
            "minecraft:chicken",
            "minecraft:beef",
            // fish
            "minecraft:tropical_fish",
            "minecraft:salmon",
            "minecraft:pufferfish",
            "minecraft:cod",
            // cooked food
            "minecraft:cooked_salmon",
            "minecraft:cooked_rabbit",
            "minecraft:cooked_porkchop",
            "minecraft:cooked_mutton",
            "minecraft:cooked_cod",
            "minecraft:cooked_chicken",
            "minecraft:cooked_beef",
            // crafted dishes
            "minecraft:suspicious_stew",
            "minecraft:rabbit_stew",
            "minecraft:pumpkin_pie",
            "minecraft:mushroom_stew",
            "minecraft:dried_kelp",
            "minecraft:cookie",
            "minecraft:bread",
            "minecraft:beetroot_soup",
            "minecraft:baked_potato",
        ],
        "minecraft:torch": ["minecraft:torch", "minecraft:redstone_torch"],
        "minecraft:all_armor": [
            // helmet
            "minecraft:leather_helmet",
            "minecraft:golden_helmet",
            "minecraft:chainmail_helmet",
            "minecraft:iron_helmet",
            "minecraft:diamond_helmet",
            "minecraft:netherite_helmet",
            // chestplate
            "minecraft:leather_chestplate",
            "minecraft:golden_chestplate",
            "minecraft:chainmail_chestplate",
            "minecraft:iron_chestplate",
            "minecraft:diamond_chestplate",
            "minecraft:netherite_chestplate",
            // leggings
            "minecraft:leather_leggings",
            "minecraft:golden_leggings",
            "minecraft:chainmail_leggings",
            "minecraft:iron_leggings",
            "minecraft:diamond_leggings",
            "minecraft:netherite_leggings",
            // boots
            "minecraft:leather_boots",
            "minecraft:golden_boots",
            "minecraft:chainmail_boots",
            "minecraft:iron_boots",
            "minecraft:diamond_boots",
            "minecraft:netherite_boots",
        ],
    };

    static readonly HostileTargetFamilies = [
        "adult_piglin",
        "arthropod",
        "bee",
        "blaze",
        "bogged",
        "breeze",
        "cavespider",
        "creaking",
        "creeper",
        "dragon",
        "drowned",
        "enderman",
        "endermite",
        "evocation_illager",
        "ghast",
        "guardian",
        "guardian_elder",
        "hoglin",
        "hoglin_adult",
        "hoglin_baby",
        "hoglin_huntable",
        "hostile",
        "husk",
        "illager",
        "magmacube",
        "monster",
        "panda_aggressive",
        "phantom",
        "piglin",
        "piglin_brute",
        "piglin_hunter",
        "pillager",
        "ravager",
        "spring",
        "shulker",
        "silverfish",
        "skeleton",
        "spider",
        "stray",
        "undead",
        "vex",
        "vindicator",
        "warden",
        "witch",
        "wither",
        "zoglin",
        "zoglin_adult",
        "zoglin_baby",
        "zombie",
        "zombie_pigman",
        "zombie_villager",
    ];
    static readonly PassiveTargetFamilies = [
        "allay",
        "animal",
        "armadillo",
        "armorer",
        "artisan",
        "axolotl",
        "baby_turtle",
        "bat",
        "blacksmith",
        "butcher",
        "camel",
        "cartographer",
        "cat",
        "chicken",
        "cleric",
        "cod",
        "cow",
        "dolphin",
        "donkey",
        "farmer",
        "fish",
        "fisherman",
        "fletcher",
        "fox",
        "frog",
        "goat",
        "horse",
        "irongolem",
        "leatherworker",
        "librarian",
        "llama",
        "mule",
        "mushroomcow",
        "nitwit",
        "ocelot",
        "pacified",
        "panda",
        "parrot_tame",
        "parrot_wild",
        "peasant",
        "pig",
        "polarbear",
        "priest",
        "pufferfish",
        "rabbit",
        "salmon",
        "sheep",
        "shepherd",
        "skeletonhorse",
        "sniffer",
        "snowgolem",
        "squid",
        "stone_mason",
        "strider",
        "strider_adult",
        "strider_baby",
        "tadpole",
        "toolsmith",
        "trader_llama",
        "tropicalfish",
        "turtle",
        "unskilled",
        "villager",
        "wandering_trader",
        "wandering_trader_despawning",
        "weaponsmith",
        "wolf",
        "zombiehorse",
    ];

    static readonly AiPlayerItemWhitelist = [
        ...GameData.ItemGroup["minecraft:weapon"],
        ...GameData.ItemGroup["minecraft:all_food"],
        ...GameData.ItemGroup["minecraft:torch"],
        ...GameData.ItemGroup["minecraft:pickaxe"],
        ...GameData.ItemGroup["minecraft:axe"],
        ...GameData.ItemGroup["minecraft:log"],
        ...GameData.ItemGroup["minecraft:ore"],
        ...GameData.ItemGroup["minecraft:resources"],
    ];

    static readonly ArmorList = [...GameData.ItemGroup["minecraft:all_armor"]];

    static readonly WavingEmotes: Array<EmoteDefinition> = [
        { propertyNumber: 1, emote: "wave_right" },
        { propertyNumber: 2, emote: "wave_left" },
        { propertyNumber: 3, emote: "wave_both" },
    ];

    static readonly CelebrationEmotes: Array<EmoteDefinition> = [{ propertyNumber: 11, emote: "clap" }];
    static readonly PunchEmotes: Array<EmoteDefinition> = [
        { propertyNumber: 1, emote: "punch_long" },
        { propertyNumber: 2, emote: "punch_mid" },
        { propertyNumber: 3, emote: "punch_short" },
    ];

    static readonly SpawnAnimations: Array<EmoteDefinition> = [
        { propertyNumber: 1, emote: "spin" },
        { propertyNumber: 2, emote: "assemble" },
        { propertyNumber: 3, emote: "dig" },
        { propertyNumber: 4, emote: "screw" },
        { propertyNumber: 5, emote: "boot" },
        { propertyNumber: 6, emote: "hero" },
    ];
}
