import { RawMessage } from "@minecraft/server";
import { AiMessageTemplates } from "Types/AiMessageTemplate";
import BroadcastUtil from "Utilities/BroadcastUtil";
import EntityUtil from "Utilities/EntityUtil";
import MathUtil from "Utilities/MathUtil";
import Trigger from "./Trigger";

type messageData = { locKey: string; translateWith: string[] | RawMessage[] | undefined; entityName: string };
export default class ChatManager extends Trigger {
    messageLibrary: AiMessageTemplates = {
        ItemRequest: {
            validMessages: [
                { message: ["gm1_sky.chat.item_request.1"] },
                { message: ["gm1_sky.chat.item_request.2"] },
                { message: ["gm1_sky.chat.item_request.3"] },
                { message: ["gm1_sky.chat.item_request.4"] },
                { message: ["gm1_sky.chat.item_request.5"] },
                { message: ["gm1_sky.chat.item_request.6"] },
                { message: ["gm1_sky.chat.item_request.7"] },
                { message: ["gm1_sky.chat.item_request.8"] },
                { message: ["gm1_sky.chat.item_request.9"] },
                { message: ["gm1_sky.chat.item_request.10"] },
                { message: ["gm1_sky.chat.item_request.11"] },
                { message: ["gm1_sky.chat.item_request.12"] },
                { message: ["gm1_sky.chat.item_request.13"] },
                { message: ["gm1_sky.chat.item_request.14"] },
                { message: ["gm1_sky.chat.item_request.15"] },
                { message: ["gm1_sky.chat.item_request.16"] },
                { message: ["gm1_sky.chat.item_request.17"] },
                { message: ["gm1_sky.chat.item_request.18"] },
                { message: ["gm1_sky.chat.item_request.19"] },
                { message: ["gm1_sky.chat.item_request.20"] },
            ],
        },
        Greeting: {
            validMessages: [
                { message: ["gm1_sky.chat.greeting.1"] },
                { message: ["gm1_sky.chat.greeting.2"] },
                { message: ["gm1_sky.chat.greeting.3"] },
                { message: ["gm1_sky.chat.greeting.4"] },
                { message: ["gm1_sky.chat.greeting.5"] },
                { message: ["gm1_sky.chat.greeting.6"] },
                { message: ["gm1_sky.chat.greeting.7"] },
                { message: ["gm1_sky.chat.greeting.8"] },
                { message: ["gm1_sky.chat.greeting.9"] },
                { message: ["gm1_sky.chat.greeting.10"] },
                { message: ["gm1_sky.chat.greeting.11"] },
                { message: ["gm1_sky.chat.greeting.12"] },
                { message: ["gm1_sky.chat.greeting.13"] },
                { message: ["gm1_sky.chat.greeting.14"] },
                { message: ["gm1_sky.chat.greeting.15"] },
                { message: ["gm1_sky.chat.greeting.16"] },
                { message: ["gm1_sky.chat.greeting.17"] },
                { message: ["gm1_sky.chat.greeting.18"] },
                { message: ["gm1_sky.chat.greeting.19"] },
                { message: ["gm1_sky.chat.greeting.20"] },
            ],
        },
        GiftItem: {
            validMessages: [
                { message: ["gm1_sky.chat.gift_item.1"] },
                { message: ["gm1_sky.chat.gift_item.2"] },
                { message: ["gm1_sky.chat.gift_item.3"] },
                { message: ["gm1_sky.chat.gift_item.4"] },
                { message: ["gm1_sky.chat.gift_item.5"] },
                { message: ["gm1_sky.chat.gift_item.6"] },
                { message: ["gm1_sky.chat.gift_item.7"] },
                { message: ["gm1_sky.chat.gift_item.8"] },
                { message: ["gm1_sky.chat.gift_item.9"] },
                { message: ["gm1_sky.chat.gift_item.10"] },
                { message: ["gm1_sky.chat.gift_item.11"] },
                { message: ["gm1_sky.chat.gift_item.12"] },
                { message: ["gm1_sky.chat.gift_item.13"] },
                { message: ["gm1_sky.chat.gift_item.14"] },
                { message: ["gm1_sky.chat.gift_item.15"] },
                { message: ["gm1_sky.chat.gift_item.16"] },
                { message: ["gm1_sky.chat.gift_item.17"] },
                { message: ["gm1_sky.chat.gift_item.18"] },
                { message: ["gm1_sky.chat.gift_item.19"] },
                { message: ["gm1_sky.chat.gift_item.20"] },
            ],
        },
        Hello: {
            validMessages: [
                { message: ["gm1_sky.chat.hello.1"] },
                { message: ["gm1_sky.chat.hello.2"] },
                { message: ["gm1_sky.chat.hello.3"] },
                { message: ["gm1_sky.chat.hello.4"] },
                { message: ["gm1_sky.chat.hello.5"] },
                { message: ["gm1_sky.chat.hello.6"] },
                { message: ["gm1_sky.chat.hello.7"] },
                { message: ["gm1_sky.chat.hello.8"] },
                { message: ["gm1_sky.chat.hello.9"] },
                { message: ["gm1_sky.chat.hello.10"] },
                { message: ["gm1_sky.chat.hello.11"] },
                { message: ["gm1_sky.chat.hello.12"] },
                { message: ["gm1_sky.chat.hello.13"] },
                { message: ["gm1_sky.chat.hello.14"] },
                { message: ["gm1_sky.chat.hello.15"] },
                { message: ["gm1_sky.chat.hello.16"] },
                { message: ["gm1_sky.chat.hello.17"] },
                { message: ["gm1_sky.chat.hello.18"] },
                { message: ["gm1_sky.chat.hello.19"] },
                { message: ["gm1_sky.chat.hello.20"] },
                { message: ["gm1_sky.chat.hello.21"] },
                { message: ["gm1_sky.chat.hello.22"] },
                { message: ["gm1_sky.chat.hello.23"] },
                { message: ["gm1_sky.chat.hello.24"] },
                { message: ["gm1_sky.chat.hello.25"] },
                { message: ["gm1_sky.chat.hello.26"] },
                { message: ["gm1_sky.chat.hello.27"] },
                { message: ["gm1_sky.chat.hello.28"] },
                { message: ["gm1_sky.chat.hello.29"] },
                { message: ["gm1_sky.chat.hello.30"] },
                { message: ["gm1_sky.chat.hello.31"] },
                { message: ["gm1_sky.chat.hello.32"] },
                { message: ["gm1_sky.chat.hello.33"] },
                { message: ["gm1_sky.chat.hello.34"] },
                { message: ["gm1_sky.chat.hello.35"] },
                { message: ["gm1_sky.chat.hello.36"] },
                { message: ["gm1_sky.chat.hello.37"] },
                { message: ["gm1_sky.chat.hello.38"] },
                { message: ["gm1_sky.chat.hello.39"] },
                { message: ["gm1_sky.chat.hello.40"] },
                { message: ["gm1_sky.chat.hello.41"] },
                { message: ["gm1_sky.chat.hello.42"] },
                { message: ["gm1_sky.chat.hello.43"] },
                { message: ["gm1_sky.chat.hello.44"] },
                { message: ["gm1_sky.chat.hello.45"] },
                { message: ["gm1_sky.chat.hello.46"] },
                { message: ["gm1_sky.chat.hello.47"] },
                { message: ["gm1_sky.chat.hello.48"] },
                { message: ["gm1_sky.chat.hello.49"] },
                { message: ["gm1_sky.chat.hello.50"] },
                { message: ["gm1_sky.chat.hello.51"] },
                { message: ["gm1_sky.chat.hello.52"] },
                { message: ["gm1_sky.chat.hello.53"] },
                { message: ["gm1_sky.chat.hello.54"] },
                { message: ["gm1_sky.chat.hello.55"] },
                { message: ["gm1_sky.chat.hello.56"] },
                { message: ["gm1_sky.chat.hello.57"] },
                { message: ["gm1_sky.chat.hello.58"] },
                { message: ["gm1_sky.chat.hello.59"] },
                { message: ["gm1_sky.chat.hello.60"] },
                { message: ["gm1_sky.chat.hello.61"] },
                { message: ["gm1_sky.chat.hello.62"] },
                { message: ["gm1_sky.chat.hello.63"] },
                { message: ["gm1_sky.chat.hello.64"] },
                { message: ["gm1_sky.chat.hello.65"] },
                { message: ["gm1_sky.chat.hello.66"] },
                { message: ["gm1_sky.chat.hello.67"] },
                { message: ["gm1_sky.chat.hello.68"] },
                { message: ["gm1_sky.chat.hello.69"] },
                { message: ["gm1_sky.chat.hello.70"] },
                { message: ["gm1_sky.chat.hello.71"] },
                { message: ["gm1_sky.chat.hello.72"] },
                { message: ["gm1_sky.chat.hello.73"] },
                { message: ["gm1_sky.chat.hello.74"] },
                { message: ["gm1_sky.chat.hello.75"] },
                { message: ["gm1_sky.chat.hello.76"] },
                { message: ["gm1_sky.chat.hello.77"] },
                { message: ["gm1_sky.chat.hello.78"] },
                { message: ["gm1_sky.chat.hello.79"] },
                { message: ["gm1_sky.chat.hello.80"] },
                { message: ["gm1_sky.chat.hello.81"] },
                { message: ["gm1_sky.chat.hello.82"] },
                { message: ["gm1_sky.chat.hello.83"] },
                { message: ["gm1_sky.chat.hello.84"] },
                { message: ["gm1_sky.chat.hello.85"] },
                { message: ["gm1_sky.chat.hello.86"] },
                { message: ["gm1_sky.chat.hello.87"] },
                { message: ["gm1_sky.chat.hello.88"] },
                { message: ["gm1_sky.chat.hello.89"] },
                { message: ["gm1_sky.chat.hello.90"] },
                { message: ["gm1_sky.chat.hello.91"] },
                { message: ["gm1_sky.chat.hello.92"] },
                { message: ["gm1_sky.chat.hello.93"] },
                { message: ["gm1_sky.chat.hello.94"] },
                { message: ["gm1_sky.chat.hello.95"] },
                { message: ["gm1_sky.chat.hello.96"] },
                { message: ["gm1_sky.chat.hello.97"] },
                { message: ["gm1_sky.chat.hello.98"] },
                { message: ["gm1_sky.chat.hello.99"] },
                { message: ["gm1_sky.chat.hello.100"] },
                { message: ["gm1_sky.chat.hello.101"] },
                { message: ["gm1_sky.chat.hello.102"] },
                { message: ["gm1_sky.chat.hello.103"] },
            ],
        },
        Goodbye: {
            validMessages: [
                { message: ["gm1_sky.chat.goodbye.1"] },
                { message: ["gm1_sky.chat.goodbye.2"] },
                { message: ["gm1_sky.chat.goodbye.3"] },
            ],
        },
        AlmostDead: {
            validMessages: [
                { message: ["gm1_sky.chat.almost_dead.1"] },
                { message: ["gm1_sky.chat.almost_dead.2"] },
                { message: ["gm1_sky.chat.almost_dead.3"] },
                { message: ["gm1_sky.chat.almost_dead.4"] },
                { message: ["gm1_sky.chat.almost_dead.5"] },
                { message: ["gm1_sky.chat.almost_dead.6"] },
                { message: ["gm1_sky.chat.almost_dead.7"] },
                { message: ["gm1_sky.chat.almost_dead.8"] },
                { message: ["gm1_sky.chat.almost_dead.9"] },
                { message: ["gm1_sky.chat.almost_dead.10"] },
                { message: ["gm1_sky.chat.almost_dead.11"] },
                { message: ["gm1_sky.chat.almost_dead.12"] },
                { message: ["gm1_sky.chat.almost_dead.13"] },
                { message: ["gm1_sky.chat.almost_dead.14"] },
                { message: ["gm1_sky.chat.almost_dead.15"] },
                { message: ["gm1_sky.chat.almost_dead.16"] },
                { message: ["gm1_sky.chat.almost_dead.17"] },
                { message: ["gm1_sky.chat.almost_dead.18"] },
            ],
        },
        Adventure: {
            validMessages: [
                { message: ["gm1_sky.chat.adventure.1"] },
                { message: ["gm1_sky.chat.adventure.2"] },
                { message: ["gm1_sky.chat.adventure.3"] },
                { message: ["gm1_sky.chat.adventure.4"] },
                { message: ["gm1_sky.chat.adventure.5"] },
                { message: ["gm1_sky.chat.adventure.6"] },
                { message: ["gm1_sky.chat.adventure.7"] },
                { message: ["gm1_sky.chat.adventure.8"] },
                { message: ["gm1_sky.chat.adventure.9"] },
                { message: ["gm1_sky.chat.adventure.10"] },
                { message: ["gm1_sky.chat.adventure.11"] },
                { message: ["gm1_sky.chat.adventure.12"] },
                { message: ["gm1_sky.chat.adventure.13"] },
                { message: ["gm1_sky.chat.adventure.14"] },
                { message: ["gm1_sky.chat.adventure.15"] },
                { message: ["gm1_sky.chat.adventure.16"] },
                { message: ["gm1_sky.chat.adventure.17"] },
                { message: ["gm1_sky.chat.adventure.18"] },
                { message: ["gm1_sky.chat.adventure.19"] },
                { message: ["gm1_sky.chat.adventure.20"] },
            ],
        },
        Random: {
            validMessages: [
                { message: ["gm1_sky.chat.random.1"] },
                { message: ["gm1_sky.chat.random.2"] },
                { message: ["gm1_sky.chat.random.3"] },
                { message: ["gm1_sky.chat.random.4"] },
                { message: ["gm1_sky.chat.random.5"] },
                { message: ["gm1_sky.chat.random.6"] },
                { message: ["gm1_sky.chat.random.7"] },
                { message: ["gm1_sky.chat.random.8"] },
                { message: ["gm1_sky.chat.random.9"] },
                { message: ["gm1_sky.chat.random.10"] },
                { message: ["gm1_sky.chat.random.11"] },
                { message: ["gm1_sky.chat.random.12"] },
                { message: ["gm1_sky.chat.random.13"] },
                { message: ["gm1_sky.chat.random.14"] },
                { message: ["gm1_sky.chat.random.15"] },
                { message: ["gm1_sky.chat.random.16"] },
                { message: ["gm1_sky.chat.random.17"] },
                { message: ["gm1_sky.chat.random.18"] },
                { message: ["gm1_sky.chat.random.19"] },
                { message: ["gm1_sky.chat.random.20"] },
                { message: ["gm1_sky.chat.random.21"] },
                { message: ["gm1_sky.chat.random.22"] },
                { message: ["gm1_sky.chat.random.23"] },
                { message: ["gm1_sky.chat.random.24"] },
                { message: ["gm1_sky.chat.random.25"] },
                { message: ["gm1_sky.chat.random.26"] },
                { message: ["gm1_sky.chat.random.27"] },
                { message: ["gm1_sky.chat.random.28"] },
                { message: ["gm1_sky.chat.random.29"] },
            ],
        },
        Respawned: {
            validMessages: [
                { message: ["gm1_sky.chat.respawned.1"] },
                { message: ["gm1_sky.chat.respawned.2"] },
                { message: ["gm1_sky.chat.respawned.3"] },
                { message: ["gm1_sky.chat.respawned.4"] },
                { message: ["gm1_sky.chat.respawned.5"] },
                { message: ["gm1_sky.chat.respawned.6"] },
                { message: ["gm1_sky.chat.respawned.7"] },
                { message: ["gm1_sky.chat.respawned.8"] },
                { message: ["gm1_sky.chat.respawned.9"] },
                { message: ["gm1_sky.chat.respawned.10"] },
                { message: ["gm1_sky.chat.respawned.11"] },
                { message: ["gm1_sky.chat.respawned.12"] },
                { message: ["gm1_sky.chat.respawned.13"] },
                { message: ["gm1_sky.chat.respawned.14"] },
                { message: ["gm1_sky.chat.respawned.15"] },
            ],
        },
        Slain: {
            validMessages: [
                { message: ["gm1_sky.chat.slain.1"] },
                { message: ["gm1_sky.chat.slain.2"] },
                { message: ["gm1_sky.chat.slain.3"] },
                { message: ["gm1_sky.chat.slain.4"] },
                { message: ["gm1_sky.chat.slain.5"] },
                { message: ["gm1_sky.chat.slain.6"] },
                { message: ["gm1_sky.chat.slain.7"] },
                { message: ["gm1_sky.chat.slain.8"] },
                { message: ["gm1_sky.chat.slain.9"] },
                { message: ["gm1_sky.chat.slain.10"] },
                { message: ["gm1_sky.chat.slain.11"] },
                { message: ["gm1_sky.chat.slain.12"] },
                { message: ["gm1_sky.chat.slain.13"] },
                { message: ["gm1_sky.chat.slain.14"] },
                { message: ["gm1_sky.chat.slain.15"] },
            ],
        },
        SlainSomeone: {
            validMessages: [
                { message: ["gm1_sky.chat.slain_someone.1"] },
                { message: ["gm1_sky.chat.slain_someone.2"] },
                { message: ["gm1_sky.chat.slain_someone.3"] },
                { message: ["gm1_sky.chat.slain_someone.4"] },
                { message: ["gm1_sky.chat.slain_someone.5"] },
                { message: ["gm1_sky.chat.slain_someone.6"] },
                { message: ["gm1_sky.chat.slain_someone.7"] },
                { message: ["gm1_sky.chat.slain_someone.8"] },
                { message: ["gm1_sky.chat.slain_someone.9"] },
                { message: ["gm1_sky.chat.slain_someone.10"] },
                { message: ["gm1_sky.chat.slain_someone.11"] },
                { message: ["gm1_sky.chat.slain_someone.12"] },
                { message: ["gm1_sky.chat.slain_someone.13"] },
                { message: ["gm1_sky.chat.slain_someone.14"] },
                { message: ["gm1_sky.chat.slain_someone.15"] },
                { message: ["gm1_sky.chat.slain_someone.16"] },
            ],
        },
        BeRightBack: {
            validMessages: [
                { message: ["gm1_sky.chat.gift_item.1"] },
                { message: ["gm1_sky.chat.gift_item.2"] },
                { message: ["gm1_sky.chat.gift_item.3"] },
                { message: ["gm1_sky.chat.gift_item.4"] },
                { message: ["gm1_sky.chat.gift_item.5"] },
                { message: ["gm1_sky.chat.gift_item.6"] },
                { message: ["gm1_sky.chat.gift_item.7"] },
                { message: ["gm1_sky.chat.gift_item.8"] },
                { message: ["gm1_sky.chat.gift_item.9"] },
                { message: ["gm1_sky.chat.gift_item.10"] },
                { message: ["gm1_sky.chat.gift_item.11"] },
                { message: ["gm1_sky.chat.gift_item.12"] },
                { message: ["gm1_sky.chat.gift_item.13"] },
                { message: ["gm1_sky.chat.gift_item.14"] },
                { message: ["gm1_sky.chat.gift_item.15"] },
                { message: ["gm1_sky.chat.gift_item.16"] },
                { message: ["gm1_sky.chat.gift_item.17"] },
                { message: ["gm1_sky.chat.gift_item.18"] },
                { message: ["gm1_sky.chat.gift_item.19"] },
                { message: ["gm1_sky.chat.gift_item.20"] },
                { message: ["gm1_sky.chat.gift_item.21"] },
                { message: ["gm1_sky.chat.gift_item.22"] },
                { message: ["gm1_sky.chat.gift_item.23"] },
                { message: ["gm1_sky.chat.gift_item.24"] },
                { message: ["gm1_sky.chat.gift_item.25"] },
                { message: ["gm1_sky.chat.gift_item.26"] },
                { message: ["gm1_sky.chat.gift_item.27"] },
                { message: ["gm1_sky.chat.gift_item.28"] },
                { message: ["gm1_sky.chat.gift_item.29"] },
                { message: ["gm1_sky.chat.gift_item.30"] },
                { message: ["gm1_sky.chat.gift_item.31"] },
                { message: ["gm1_sky.chat.gift_item.32"] },
                { message: ["gm1_sky.chat.gift_item.33"] },
                { message: ["gm1_sky.chat.gift_item.34"] },
                { message: ["gm1_sky.chat.gift_item.35"] },
                { message: ["gm1_sky.chat.gift_item.36"] },
                { message: ["gm1_sky.chat.gift_item.37"] },
                { message: ["gm1_sky.chat.gift_item.38"] },
                { message: ["gm1_sky.chat.gift_item.39"] },
                { message: ["gm1_sky.chat.gift_item.40"] },
            ],
        },
        FollowMe: {
            validMessages: [{ message: ["gm1_sky.chat.follow_me.1"] }, { message: ["gm1_sky.chat.follow_me.2"] }],
        },
        GoAway: {
            validMessages: [{ message: ["gm1_sky.chat.go_away.1"] }, { message: ["gm1_sky.chat.go_away.2"] }],
        },
        FightingMonsters: {
            validMessages: [
                { message: ["gm1_sky.chat.fighting_monsters.1"] },
                { message: ["gm1_sky.chat.fighting_monsters.2"] },
                { message: ["gm1_sky.chat.fighting_monsters.3"] },
                { message: ["gm1_sky.chat.fighting_monsters.4"] },
                { message: ["gm1_sky.chat.fighting_monsters.5"] },
                { message: ["gm1_sky.chat.fighting_monsters.6"] },
                { message: ["gm1_sky.chat.fighting_monsters.7"] },
                { message: ["gm1_sky.chat.fighting_monsters.8"] },
                { message: ["gm1_sky.chat.fighting_monsters.9"] },
                { message: ["gm1_sky.chat.fighting_monsters.10"] },
                { message: ["gm1_sky.chat.fighting_monsters.11"] },
                { message: ["gm1_sky.chat.fighting_monsters.12"] },
                { message: ["gm1_sky.chat.fighting_monsters.13"] },
                { message: ["gm1_sky.chat.fighting_monsters.14"] },
                { message: ["gm1_sky.chat.fighting_monsters.15"] },
                { message: ["gm1_sky.chat.fighting_monsters.16"] },
                { message: ["gm1_sky.chat.fighting_monsters.17"] },
                { message: ["gm1_sky.chat.fighting_monsters.18"] },
                { message: ["gm1_sky.chat.fighting_monsters.19"] },
                { message: ["gm1_sky.chat.fighting_monsters.20"] },
                { message: ["gm1_sky.chat.fighting_monsters.21"] },
                { message: ["gm1_sky.chat.fighting_monsters.22"] },
                { message: ["gm1_sky.chat.fighting_monsters.23"] },
                { message: ["gm1_sky.chat.fighting_monsters.24"] },
                { message: ["gm1_sky.chat.fighting_monsters.25"] },
                { message: ["gm1_sky.chat.fighting_monsters.26"] },
                { message: ["gm1_sky.chat.fighting_monsters.27"] },
                { message: ["gm1_sky.chat.fighting_monsters.28"] },
                { message: ["gm1_sky.chat.fighting_monsters.29"] },
                { message: ["gm1_sky.chat.fighting_monsters.30"] },
                { message: ["gm1_sky.chat.fighting_monsters.31"] },
                { message: ["gm1_sky.chat.fighting_monsters.32"] },
                { message: ["gm1_sky.chat.fighting_monsters.33"] },
                { message: ["gm1_sky.chat.fighting_monsters.34"] },
                { message: ["gm1_sky.chat.fighting_monsters.35"] },
                { message: ["gm1_sky.chat.fighting_monsters.36"] },
                { message: ["gm1_sky.chat.fighting_monsters.37"] },
                { message: ["gm1_sky.chat.fighting_monsters.38"] },
                { message: ["gm1_sky.chat.fighting_monsters.39"] },
                { message: ["gm1_sky.chat.fighting_monsters.40"] },
                { message: ["gm1_sky.chat.fighting_monsters.41"] },
                { message: ["gm1_sky.chat.fighting_monsters.42"] },
                { message: ["gm1_sky.chat.fighting_monsters.43"] },
                { message: ["gm1_sky.chat.fighting_monsters.44"] },
                { message: ["gm1_sky.chat.fighting_monsters.45"] },
                { message: ["gm1_sky.chat.fighting_monsters.46"] },
                { message: ["gm1_sky.chat.fighting_monsters.47"] },
                { message: ["gm1_sky.chat.fighting_monsters.48"] },
                { message: ["gm1_sky.chat.fighting_monsters.49"] },
                { message: ["gm1_sky.chat.fighting_monsters.50"] },
                { message: ["gm1_sky.chat.fighting_monsters.51"] },
                { message: ["gm1_sky.chat.fighting_monsters.52"] },
                { message: ["gm1_sky.chat.fighting_monsters.53"] },
                { message: ["gm1_sky.chat.fighting_monsters.54"] },
                { message: ["gm1_sky.chat.fighting_monsters.55"] },
                { message: ["gm1_sky.chat.fighting_monsters.56"] },
                { message: ["gm1_sky.chat.fighting_monsters.57"] },
                { message: ["gm1_sky.chat.fighting_monsters.58"] },
                { message: ["gm1_sky.chat.fighting_monsters.59"] },
                { message: ["gm1_sky.chat.fighting_monsters.60"] },
                { message: ["gm1_sky.chat.fighting_monsters.61"] },
                { message: ["gm1_sky.chat.fighting_monsters.62"] },
                { message: ["gm1_sky.chat.fighting_monsters.63"] },
                { message: ["gm1_sky.chat.fighting_monsters.64"] },
                { message: ["gm1_sky.chat.fighting_monsters.65"] },
                { message: ["gm1_sky.chat.fighting_monsters.66"] },
                { message: ["gm1_sky.chat.fighting_monsters.67"] },
                { message: ["gm1_sky.chat.fighting_monsters.68"] },
                { message: ["gm1_sky.chat.fighting_monsters.69"] },
                { message: ["gm1_sky.chat.fighting_monsters.70"] },
                { message: ["gm1_sky.chat.fighting_monsters.71"] },
                { message: ["gm1_sky.chat.fighting_monsters.72"] },
                { message: ["gm1_sky.chat.fighting_monsters.73"] },
                { message: ["gm1_sky.chat.fighting_monsters.74"] },
                { message: ["gm1_sky.chat.fighting_monsters.75"] },
                { message: ["gm1_sky.chat.fighting_monsters.76"] },
                { message: ["gm1_sky.chat.fighting_monsters.77"] },
                { message: ["gm1_sky.chat.fighting_monsters.78"] },
                { message: ["gm1_sky.chat.fighting_monsters.79"] },
                { message: ["gm1_sky.chat.fighting_monsters.80"] },
                { message: ["gm1_sky.chat.fighting_monsters.81"] },
            ],
        },
        FleeingMonsters: {
            validMessages: [
                { message: ["gm1_sky.chat.fleeing_monsters.1"] },
                { message: ["gm1_sky.chat.fleeing_monsters.2"] },
                { message: ["gm1_sky.chat.fleeing_monsters.3"] },
                { message: ["gm1_sky.chat.fleeing_monsters.4"] },
                { message: ["gm1_sky.chat.fleeing_monsters.5"] },
                { message: ["gm1_sky.chat.fleeing_monsters.6"] },
                { message: ["gm1_sky.chat.fleeing_monsters.7"] },
                { message: ["gm1_sky.chat.fleeing_monsters.8"] },
                { message: ["gm1_sky.chat.fleeing_monsters.9"] },
                { message: ["gm1_sky.chat.fleeing_monsters.10"] },
                { message: ["gm1_sky.chat.fleeing_monsters.11"] },
                { message: ["gm1_sky.chat.fleeing_monsters.12"] },
                { message: ["gm1_sky.chat.fleeing_monsters.13"] },
                { message: ["gm1_sky.chat.fleeing_monsters.14"] },
                { message: ["gm1_sky.chat.fleeing_monsters.15"] },
                { message: ["gm1_sky.chat.fleeing_monsters.16"] },
                { message: ["gm1_sky.chat.fleeing_monsters.17"] },
                { message: ["gm1_sky.chat.fleeing_monsters.18"] },
                { message: ["gm1_sky.chat.fleeing_monsters.19"] },
                { message: ["gm1_sky.chat.fleeing_monsters.20"] },
                { message: ["gm1_sky.chat.fleeing_monsters.21"] },
                { message: ["gm1_sky.chat.fleeing_monsters.22"] },
            ],
        },
        FunFact: {
            validMessages: [{ message: ["gm1_sky.chat.fun_fact.1"] }],
        },
        ReplyAffirmative: {
            validMessages: [
                { message: ["gm1_sky.chat.reply_affirmative.1"] },
                { message: ["gm1_sky.chat.reply_affirmative.2"] },
                { message: ["gm1_sky.chat.reply_affirmative.3"] },
                { message: ["gm1_sky.chat.reply_affirmative.4"] },
                { message: ["gm1_sky.chat.reply_affirmative.5"] },
                { message: ["gm1_sky.chat.reply_affirmative.6"] },
                { message: ["gm1_sky.chat.reply_affirmative.7"] },
                { message: ["gm1_sky.chat.reply_affirmative.8"] },
                { message: ["gm1_sky.chat.reply_affirmative.9"] },
                { message: ["gm1_sky.chat.reply_affirmative.10"] },
                { message: ["gm1_sky.chat.reply_affirmative.11"] },
                { message: ["gm1_sky.chat.reply_affirmative.12"] },
                { message: ["gm1_sky.chat.reply_affirmative.13"] },
                { message: ["gm1_sky.chat.reply_affirmative.14"] },
                { message: ["gm1_sky.chat.reply_affirmative.15"] },
                { message: ["gm1_sky.chat.reply_affirmative.16"] },
                { message: ["gm1_sky.chat.reply_affirmative.17"] },
                { message: ["gm1_sky.chat.reply_affirmative.18"] },
                { message: ["gm1_sky.chat.reply_affirmative.19"] },
                { message: ["gm1_sky.chat.reply_affirmative.20"] },
                { message: ["gm1_sky.chat.reply_affirmative.21"] },
                { message: ["gm1_sky.chat.reply_affirmative.22"] },
                { message: ["gm1_sky.chat.reply_affirmative.23"] },
                { message: ["gm1_sky.chat.reply_affirmative.24"] },
                { message: ["gm1_sky.chat.reply_affirmative.25"] },
                { message: ["gm1_sky.chat.reply_affirmative.26"] },
                { message: ["gm1_sky.chat.reply_affirmative.27"] },
                { message: ["gm1_sky.chat.reply_affirmative.28"] },
            ],
        },
        ReplyNegative: {
            validMessages: [
                { message: ["gm1_sky.chat.reply_negative.1"] },
                { message: ["gm1_sky.chat.reply_negative.2"] },
                { message: ["gm1_sky.chat.reply_negative.3"] },
                { message: ["gm1_sky.chat.reply_negative.4"] },
                { message: ["gm1_sky.chat.reply_negative.5"] },
                { message: ["gm1_sky.chat.reply_negative.6"] },
                { message: ["gm1_sky.chat.reply_negative.7"] },
                { message: ["gm1_sky.chat.reply_negative.8"] },
                { message: ["gm1_sky.chat.reply_negative.9"] },
                { message: ["gm1_sky.chat.reply_negative.10"] },
                { message: ["gm1_sky.chat.reply_negative.11"] },
                { message: ["gm1_sky.chat.reply_negative.12"] },
                { message: ["gm1_sky.chat.reply_negative.13"] },
                { message: ["gm1_sky.chat.reply_negative.14"] },
                { message: ["gm1_sky.chat.reply_negative.15"] },
                { message: ["gm1_sky.chat.reply_negative.16"] },
                { message: ["gm1_sky.chat.reply_negative.17"] },
                { message: ["gm1_sky.chat.reply_negative.18"] },
                { message: ["gm1_sky.chat.reply_negative.19"] },
                { message: ["gm1_sky.chat.reply_negative.20"] },
                { message: ["gm1_sky.chat.reply_negative.21"] },
                { message: ["gm1_sky.chat.reply_negative.22"] },
                { message: ["gm1_sky.chat.reply_negative.23"] },
                { message: ["gm1_sky.chat.reply_negative.24"] },
                { message: ["gm1_sky.chat.reply_negative.25"] },
            ],
        },
        ReplyNeutral: {
            validMessages: [
                { message: ["gm1_sky.chat.reply_neutral.1"] },
                { message: ["gm1_sky.chat.reply_neutral.2"] },
                { message: ["gm1_sky.chat.reply_neutral.3"] },
                { message: ["gm1_sky.chat.reply_neutral.4"] },
                { message: ["gm1_sky.chat.reply_neutral.5"] },
                { message: ["gm1_sky.chat.reply_neutral.6"] },
                { message: ["gm1_sky.chat.reply_neutral.7"] },
                { message: ["gm1_sky.chat.reply_neutral.8"] },
                { message: ["gm1_sky.chat.reply_neutral.9"] },
                { message: ["gm1_sky.chat.reply_neutral.10"] },
                { message: ["gm1_sky.chat.reply_neutral.11"] },
                { message: ["gm1_sky.chat.reply_neutral.12"] },
                { message: ["gm1_sky.chat.reply_neutral.13"] },
                { message: ["gm1_sky.chat.reply_neutral.14"] },
                { message: ["gm1_sky.chat.reply_neutral.15"] },
                { message: ["gm1_sky.chat.reply_neutral.16"] },
                { message: ["gm1_sky.chat.reply_neutral.17"] },
                { message: ["gm1_sky.chat.reply_neutral.18"] },
                { message: ["gm1_sky.chat.reply_neutral.19"] },
                { message: ["gm1_sky.chat.reply_neutral.20"] },
                { message: ["gm1_sky.chat.reply_neutral.21"] },
                { message: ["gm1_sky.chat.reply_neutral.22"] },
            ],
        },
        ReplyChaotic: {
            validMessages: [{ message: ["gm1_sky.chat.reply_chaotic.1"] }, { message: ["gm1_sky.chat.reply_chaotic.2"] }],
        },
        Gratitude: {
            validMessages: [
                { message: ["gm1_sky.chat.gratitude.1"] },
                { message: ["gm1_sky.chat.gratitude.2"] },
                { message: ["gm1_sky.chat.gratitude.3"] },
                { message: ["gm1_sky.chat.gratitude.4"] },
                { message: ["gm1_sky.chat.gratitude.5"] },
            ],
        },
        Waving: {
            validMessages: [{ message: ["is §aWaving§r."] }, { message: ["'s arm is tired from so much §aWaving§r."] }],
        },
        Celebrating: {
            validMessages: [{ message: ["is §aCelebrating§r."] }, { message: [": Congratulations!"] }],
        },
        Hungry: {
            validMessages: [
                { message: ["gm1_sky.chat.hungry.1"] },
                { message: ["gm1_sky.chat.hungry.2"] },
                { message: ["gm1_sky.chat.hungry.3"] },
                { message: ["gm1_sky.chat.hungry.4"] },
                { message: ["gm1_sky.chat.hungry.5"] },
                { message: ["gm1_sky.chat.hungry.6"] },
                { message: ["gm1_sky.chat.hungry.7"] },
            ],
        },
        ChopTree: {
            validMessages: [
                { message: ["gm1_sky.chat.chop_tree.1"] },
                { message: ["gm1_sky.chat.chop_tree.2"] },
                { message: ["gm1_sky.chat.chop_tree.3"] },
                { message: ["gm1_sky.chat.chop_tree.4"] },
                { message: ["gm1_sky.chat.chop_tree.5"] },
                { message: ["gm1_sky.chat.chop_tree.6"] },
                { message: ["gm1_sky.chat.chop_tree.7"] },
            ],
        },
        MineOre: {
            validMessages: [
                { message: ["gm1_sky.chat.mine_ore.1"] },
                { message: ["gm1_sky.chat.mine_ore.2"] },
                { message: ["gm1_sky.chat.mine_ore.3"] },
                { message: ["gm1_sky.chat.mine_ore.4"] },
                { message: ["gm1_sky.chat.mine_ore.5"] },
                { message: ["gm1_sky.chat.mine_ore.6"] },
                { message: ["gm1_sky.chat.mine_ore.7"] },
            ],
        },
        Sleep: {
            validMessages: [
                { message: ["gm1_sky.chat.sleep.1"] },
                { message: ["gm1_sky.chat.sleep.2"] },
                { message: ["gm1_sky.chat.sleep.3"] },
                { message: ["gm1_sky.chat.sleep.4"] },
                { message: ["gm1_sky.chat.sleep.5"] },
                { message: ["gm1_sky.chat.sleep.6"] },
                { message: ["gm1_sky.chat.sleep.7"] },
            ],
        },
    };

    messageQueue: Array<messageData> = [];
    messageInterval: number = 5;
    messageDelay: number = 1;

    init() {
        this.interval(() => this.checkMessageQueue(), this.messageInterval);

        this.onGameEvent("aiPlayerMessage", (aiPlayer, name, goal, percent, data) => {
            if (!EntityUtil.isValid(aiPlayer)) return;
            if (percent < 0) percent = 0.0;
            if (percent > 1) percent = 1.0;
            if (Math.random() > percent) return;

            const message = this.chooseMessageTemplate(goal);

            if (!message) {
                BroadcastUtil.debug(goal + " does not exist in AiMessageTemplates");
                return;
            }
            message.forEach((element) => {
                this.messageQueue.push({ locKey: element, translateWith: data, entityName: name });
            });
        });
    }

    checkMessageQueue() {
        if (this.messageDelay > 0) {
            this.messageDelay--;
            return;
        }

        if (this.messageQueue.length && !this.messageDelay) {
            if (this.messageQueue[0].translateWith != undefined) {
                BroadcastUtil.translate(
                    this.messageQueue[0].locKey,
                    this.messageQueue[0].translateWith,
                    null,
                    `<${this.messageQueue[0].entityName}> `
                );
            } else {
                BroadcastUtil.translate(this.messageQueue[0].locKey, null, null, `<${this.messageQueue[0].entityName}> `);
            }
            this.messageQueue.shift();
            this.messageDelay = MathUtil.randomInt(8, 16);
        }
    }

    chooseMessageTemplate(goal: string) {
        const messagePool = this.messageLibrary[goal]?.validMessages;
        if (!messagePool) return;

        return messagePool[MathUtil.randomInt(0, messagePool.length)].message;
    }
}
